#!/usr/bin/env python3

import rvcprint
import numpy as np
import matplotlib.pyplot as plt
from machinevisiontoolbox import *
from matplotlib.ticker import ScalarFormatter
from matplotlib import cm

function A = jacA(P1,P2,P3,T1,T2,T3,f,qx,qy,qz,rho,u0,v0)
#JACA
#    A = JACA(P1,P2,P3,T1,T2,T3,F,QX,QY,QZ,RHO,U0,V0)

#    This function was generated by the Symbolic Math Toolbox version 6.3.
#    02-Nov-2015 20:25:47

t2 = qy.^2
t3 = qz.^2
t4 = qx.^2
t5 = t2.*2.0
t6 = t4.*2.0
t7 = t5+t6-1.0
t8 = qx.*qz.*2.0
t9 = -t2-t3-t4+1.0
t10 = sqrt(t9)
t11 = conj(t10)
t12 = qy.*t11.*2.0
t13 = t8+t12
t14 = qy.*qz.*2.0
t17 = qx.*t11.*2.0
t15 = t14-t17
t16 = P3.*t7
t18 = T1.*t13
t19 = T2.*t15
t28 = T3.*t7
t29 = P1.*t13
t30 = P2.*t15
t20 = t16+t18+t19-t28-t29-t30
t21 = 1.0./rho
t22 = t3.*2.0
t23 = t5+t22-1.0
t24 = qx.*qy.*2.0
t25 = qz.*t11.*2.0
t26 = t24+t25
t27 = t8-t12
t31 = 1.0./t20
t32 = t20.*u0
t33 = P1.*t23
t34 = T2.*t26
t35 = T3.*t27
t40 = T1.*t23
t41 = P2.*t26
t42 = P3.*t27
t36 = t33+t34+t35-t40-t41-t42
t37 = f.*t21.*t36
t38 = t32+t37
t39 = 1.0./t20.^2
t43 = qz.*2.0
t44 = 1.0./t11
t48 = qx.*qy.*t44.*2.0
t45 = t43-t48
t46 = t11.*2.0
t54 = t4.*t44.*2.0
t47 = t46-t54
t49 = qy.*2.0
t66 = qx.*qz.*t44.*2.0
t50 = t49-t66
t51 = t43+t48
t52 = P3.*qx.*4.0
t53 = T1.*t45
t55 = P2.*t47
t86 = T3.*qx.*4.0
t87 = P1.*t45
t88 = T2.*t47
t56 = t52+t53+t55-t86-t87-t88
t60 = t2.*t44.*2.0
t57 = t46-t60
t58 = qx.*2.0
t65 = qy.*qz.*t44.*2.0
t59 = t58-t65
t61 = P3.*qy.*4.0
t62 = T2.*t51
t63 = T1.*t57
t89 = T3.*qy.*4.0
t90 = P2.*t51
t91 = P1.*t57
t64 = t61+t62+t63-t89-t90-t91
t67 = t49+t66
t68 = t58+t65
t94 = t3.*t44.*2.0
t69 = t46-t94
t70 = P1.*t59
t71 = P2.*t67
t92 = T1.*t59
t93 = T2.*t67
t72 = t70+t71-t92-t93
t73 = t6+t22-1.0
t74 = t24-t25
t75 = t14+t17
t76 = t20.*v0
t77 = T2.*t73
t78 = P1.*t74
t79 = P3.*t75
t82 = P2.*t73
t83 = T1.*t74
t84 = T3.*t75
t80 = t77+t78+t79-t82-t83-t84
t85 = f.*t21.*t80
t81 = t76-t85
A = reshape([t31.*(t13.*u0-f.*t21.*t23)-t13.*t38.*t39,t31.*(t13.*v0+f.*t21.*t74)-t13.*t39.*t81,t31.*(t15.*u0+f.*t21.*t26)-t15.*t38.*t39,t31.*(t15.*v0-f.*t21.*t73)-t15.*t39.*t81,-t31.*(t7.*u0-f.*t21.*t27)+t7.*t38.*t39,-t31.*(t7.*v0-f.*t21.*t75)+t7.*t39.*t81,t31.*(t56.*u0-f.*t21.*(P2.*t50+P3.*t51-T2.*t50-T3.*t51))-t38.*t39.*t56,t31.*(t56.*v0+f.*t21.*(P2.*qx.*4.0-P3.*t47-P1.*t67-T2.*qx.*4.0+T3.*t47+T1.*t67))-t39.*t56.*t81,t31.*(t64.*u0+f.*t21.*(P1.*qy.*4.0+P3.*t57-P2.*t59-T1.*qy.*4.0-T3.*t57+T2.*t59))-t38.*t39.*t64,t31.*(t64.*v0-f.*t21.*(P3.*t45+P1.*t68-T3.*t45-T1.*t68))-t39.*t64.*t81,-t31.*(t72.*u0-f.*t21.*(P1.*qz.*4.0-P2.*t69-P3.*t68-T1.*qz.*4.0+T2.*t69+T3.*t68))+t38.*t39.*t72,-t31.*(t72.*v0-f.*t21.*(P2.*qz.*4.0-P3.*t50+P1.*t69-T2.*qz.*4.0+T3.*t50-T1.*t69))+t39.*t72.*t81],[2,6])

